### ISSUE TITLE
StaticTools.dlopen returns Ptr{StaticTools.DYLIB} @0x0000000000000000

### ISSUE THREAD

**Issue by mdmaas** [brenhinkeller/StaticTools.jl#15]
I'm calling a C shared library, and I found that I can't use `StaticTools.dlopen` and have to rely on `Libdl.dlopen` instead. 

I think the problem is that `StaticTools.dlopen` returns `Ptr{StaticTools.DYLIB} @0x0000000000000000`.

Subsequent call to `StaticTools.dlopen` returns `Ptr{Nothing} @0x0000000000000000`. 

And eventually static compilation crashes.

Minimal example I could come up with:

```
using StaticTools, StaticCompiler, Libdl

### Let's define a C function
C_code= """
       double mean(double a, double b) {
         return (a+b) / 2;
       }
       """
Clib=tempname()
open(`gcc -fPIC -O3 -xc -shared -o $(Clib * "." * Libdl.dlext) -`, "w") do f
    print(f, C_code)
end

# This doesn't work
lib = StaticTools.dlopen(Clib)
mean = StaticTools.dlsym(lib, c"mean")

# This works
lib = Libdl.dlopen(Clib)
mean = Libdl.dlsym(lib, "mean")

function call_mean(a,b)
    ra, rb = Ref(a), Ref(b)
    GC.@preserve ra rb begin
        pa, pb = pointer_from_objref(ra), pointer_from_objref(rb)
        return @ptrcall mean(pa::Ptr{Nothing}, pb::Ptr{Nothing})::Float64
    end
end

call_mean(2.1,1.2) 
```

**Comment by brenhinkeller** [comment]
Thanks for the issue! It looks like the problem may just be that `Clib` doesn't include the extension, and that `Libdl.dlopen` apparently auto-appends it when missing but `StaticToold.dlopen` doesn't

**Comment by mdmaas** [comment]
Great, this is a minor issue indeed. Matching the API of `Libdl` sounds like a reasonable idea.
