### ISSUE TITLE
Null termination issues in StaticString

### ISSUE THREAD

**Issue by tshort** [brenhinkeller/StaticTools.jl#2]
Here are some notes:

* `getindex` doesn't add a null termination as noted in a comment.
* `display` is broken without null termination. Maybe this should use `length` instead of the termination. 
* `length` should be `N-1` and not count the null at the end.
* Should `codeunits` include the termination? It doesn't for a String.

Could the null termination be removed? I don't think Julia strings need it.

**Comment by brenhinkeller** [comment]
My initial reasoning for including null-termination in `codeunits` and in `length` and etc. is basically just that this is a low-level package where implementation details really matter, so my general instinct is to expose the nitty-gritty details that are often otherwise hidden -- but I could probably be convinced to go the other way on this

**Comment by brenhinkeller** [comment]
Also: hooray, first issue :tada:

**Comment by brenhinkeller** [comment]
One option may be to have getindex on ranges return a `StaticSubString` view type which is explicitly not null-terminated and dispatches to methods that are aware of that

**Comment by tshort** [comment]
Null termination for output is a good consideration. But, we could add the null termination prior to passing to output functions. 

I don't think `getindex` should be a view. That doesn't mesh well with other defaults in Base.

Regarding `codeunits` and `length`, I don't think we want the null termination to show up in these. They don't for normal Strings. We also want `c"abc" == "abc"`. That's currently broken.

Also, I see that `MallocString` has these same issues. Maybe we could do what Base does and allocate the null termination but keep it hidden. 

Semi-relevant Julia issues: https://github.com/JuliaLang/julia/pull/10994, https://github.com/JuliaLang/julia/pull/16731, https://github.com/JuliaLang/julia/issues/7036

**Comment by brenhinkeller** [comment]
So just an update on the current status of this:
```

julia> length(c"asdf") == length(m"asdf") == length("asdf") == 4
true

julia> c"asdf" == m"asdf" == "asdf"
true
```
We still differ from  Base, however, in including the null termination in `codeunits`, `ncodeunits`, and `sizeof`. 

What do people think, should we change those to hide the null termination as well?

**Comment by brenhinkeller** [comment]
Given no objections, I'm going to go ahead and close this as completed, but feel free to restart the discussion if it seems like we should go farther!
