### ISSUE TITLE
LoopVectorization and 32-bit support

### ISSUE THREAD

**Issue by tshort** [brenhinkeller/StaticTools.jl#52]
Is there any way we can split off support of LoopVectorization into an extension or something?

I'd like to support 32-bit systems for StaticCompiler, and LoopVectorization chokes on 32-bit systems.

Other ideas?

**Comment by brenhinkeller** [comment]
Would it be enough to just disable the LV tests on 32-bit systems?

**Comment by tshort** [comment]
I was hitting [this](https://github.com/JuliaSIMD/LoopVectorization.jl/issues/501), and it was fixed last night in LV. So, I think we're good.
